export const songs = [
    {
      name: "Dreamer",
      artist: "Alan Walker",
      path: "https://github.com/Lateblm/yt-music-player/raw/main/assets/song1.mp3",
      image: "https://raw.githubusercontent.com/Lateblm/yt-music-player/main/assets/img1.jpg",
      lyrics: ["..."],
    },

    {
      name: "Voyage",
      artist: "PLEEG",
      path: "https://github.com/Lateblm/yt-music-player/raw/main/assets/song2.mp3",
      image: "https://raw.githubusercontent.com/Lateblm/yt-music-player/main/assets/img2.jpg",
      lyrics: ["..."],
    },

    {
      name: "2AM (feat. shi’tz)",
      artist: "shi'tz, SIIK, WYKO",
      path: "./assets/song3.mp3",
      image: "./assets/img3.jpg",
      lyrics: [
        "I think it's about fuckin' time",
        "Fuckin' time",
        "I think it's about fuckin' time",
        "Fuckin' time",
        "I'ma break yo neck",
        "I think it's about fuckin' time",
        "I think it's about fuckin' time",
        "Yeah, it's ya boy shi’tz",
        "Let's go",
        "2AM, sippin' on some Hennessy",
        "Cruising down with my two-seater",
        "Spin a couple racks on some dope shit",
        "I got them boys lit, yes, it is what it is",
        "You wanna get inside but you gotta know the price",
        "I'm about to take what's mine",
        "I think it's about fuckin' time",
        "I think it's about fuckin' time",
        "I'ma break yo neck",
        "I'm about to take what's mine",
        "I think it's about fuckin' time",
        "I think it's about fuckin' time",
      ],
    },

    {
      name: "Let's Go!",
      artist: "Lensko",
      path: "./assets/song4.mp3",
      image: "./assets/img4.jpg",
      lyrics: ["..."],
    },

    {
      name: "Symbolism",
      artist: "Electro-Light",
      path: "./assets/song5.mp3",
      image: "./assets/img5.jpg",
      lyrics: ["..."],
    },

    {
      name: "Nekozilla",
      artist: "Different Heaven",
      path: "./assets/song6.mp3",
      image: "./assets/img6.jpg",
      lyrics: ["..."],
    },
    {
      name: "Savannah",
      artist: "Diviners, Philly K.",
      path: "./assets/song7.mp3",
      image: "./assets/img7.jpg",
      lyrics: [
        "Lions roaring in the morning sun",
        "Searching for a longer day",
        "People feelin' like the light has just come",
        "We must never stop the way, yeah",
        "Birds are chirping, and I hear my name",
        "Grass is green and so alive",
        "Life is happy, but it's so insane",
        "We must merely make a strife",
        "Savannah",
        "I'm coming home",
        "Savannah",
        "We'll never be alone",
        "Savannah",
        "The beauty of the world",
        "Savannah",
        "Let's all take a whirl",
        "Savannah",
        "Lions gone and come",
        "The birds have just begun",
        "We will always take a stand",
        "For the people, for the land",
        "Let's go back to when we were young",
        "For the animals we stand",
        "Let's go back to when trees were swung",
        "Kids across the land",
        "Savannah",
        "I'm coming home",
        "Savannah",
        "We'll never be alone",
        "Savannah",
        "The beauty of the world",
        "Savannah",
        "Let's all take a whirl",
        "Savannah",
        "I'm coming home",
        "Savannah",
        "We'll never be alone",
        "Savannah",
        "The beauty of the world",
        "Savannah",
        "Let's all take a whirl",
        "Savannah",
        "I'm coming home",
        "Savannah",
        "We'll never be alone",
        "Savannah",
      ],
    },
  ]
